/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>
/* Header for class LightR */

#ifndef _Included_LightR
#define _Included_LightR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LightR
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT int64_t JNICALL Java_LightR_init
  (JNIEnv *, jobject, jstring)

#ifdef __cplusplus
}
#endif
#endif
